name: PMD Analysis

on: [push, pull_request]

jobs:
  pmd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Install PMD
        run: |
          wget https://github.com/pmd/pmd/releases/latest/download/pmd-bin.zip
          unzip pmd-bin.zip
          mv pmd-bin-* pmd
          echo "$GITHUB_WORKSPACE/pmd/bin" >> $GITHUB_PATH

      - name: Run PMD and save results
        run: |
          mkdir -p pmd-reports
          pmd check -d . -R ruleset.xml -f text -r pmd-reports/pmd-results.txt

      - name: Upload PMD results
        uses: actions/upload-artifact@v4
        with:
          name: pmd-report
          path: pmd-reports/pmd-results.txt
